#!/bin/bash
### BEGIN INIT INFO
# Provides:          eyepaste
# Required-Start:    $remote_fs $syslog postfix redis-server
# Required-Stop:     $remote_fs $syslog postfix redis-server
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: eyepaste smpt server
# Description:       eyepaste smpt server
### END INIT INFO

# Author: Jon Moniaci <jonmoniaci [at] gmail.com>

# This is an example init.d script, currently tested on Debian squeeze

# change APP_ROOT and RUBY to match your eyepaste and ruby installation
APP_ROOT="/home/eyepaste/eyepaste_app/current"
RUBY="/usr/local/rvm/wrappers/ruby-1.9.3-p392/ruby"
USER="eyepaste"

DESC="Eyepaste SMTP server"
NAME=eyepaste_smtp
SCRIPT="$APP_ROOT/scripts/smtp_server_control.rb"

cd "$APP_ROOT"

run_cmd() {
  su $USER -c "$1"
}

case $1 in
  start)
    run_cmd "$RUBY $SCRIPT start"
    run_cmd "$RUBY $SCRIPT status"
  ;;
  stop)
    run_cmd "$RUBY $SCRIPT stop"
  ;;
  restart)
    run_cmd "$RUBY $SCRIPT restart"
    run_cmd "$RUBY $SCRIPT status"
  ;;
  reload)
    run_cmd "$RUBY $SCRIPT reload"
    run_cmd "$RUBY $SCRIPT status"
  ;;
  status)
    run_cmd "$RUBY $SCRIPT status"
  ;;
  *)
    echo "usage: $0 (start|stop|restart|reload|status)"
  ;;
esac
